import ren_soundex as soundex
import testclass
s = soundex.soundexer()
print(s.soundex("jjjjj"))
print(s.soundex(""))
print(s.soundex("125125"))
print(s.soundex("-1125"))
print(s.soundex("!%!%)!@&(%!@&*(&@!(*$&!@($"))
print(s.soundex("asfasfasfasf"))
print(s.soundex("ashcraft"), "A261")
print(s.soundex("ashcroft"), "A261")
print(s.soundex("bbbbbbbbbb"))
print(s.soundex("Honeyman"), "H555")
print(s.soundex("Robert"), "R163")
print(s.soundex("Rupert"), "R163")
print(s.soundex("Rubin"), "R150")
print(s.soundex("tymczak"), "T522")
print(s.soundex("Pfister"), "P236")
